title: Teoría Musical para Ukelele
description: Repositorio completo de teoría musical aplicada al ukelele con un repertorio de canciones.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
