title: Teoría Musical para Ukelele
description: Página web de teoría musical aplicada al ukelele con un repertorio de canciones.
url: https://esteban-kroh.github.io/musica/
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
