title: Teoría Musical para Ukelele
description: Repositorio completo de teoría musical aplicada al ukelele con un extenso repertorio de canciones organizadas por géneros.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Configuración adicional para GitHub Pages
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# URLs y navegación
url: ""
baseurl: ""

# Configuración de archivos
include:
  - _pages
  - assets
  - teoria
  - canciones

# SEO
lang: es
author: "Esteban"
