services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
    command: pnpm run dev

  cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
